version: '3.8'

services:
  web:
    build:
      context: ./UserService.WebApi
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # Проброс порта для веб-приложения
    depends_on:
      - db
    networks:
      - base-deploy

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword # Что то не так с паролем не может авторизоватся надо доразобраться
    ports:
      - "5432:5432"
    networks:
      - base-deploy
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:  # Определение volume для PostgreSQL

networks:
  base-deploy:
    driver: bridge
